/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin Manjarrez
 */
public class BarraMac extends javax.swing.JPanel {
    protected Lienzo l = new Lienzo(this);
    protected String nombreIconos="icono1.png,icono2.png,icono3.png,icono4.png";
    /**
     * Creates new form BarraMac
     */
    public BarraMac() {
        initComponents();
        l.setSize(500,100);
        l.setLocation(0,0);
        this.add(l);
    }
    public int valorSeleccinado() {
        return l.iconoSeleccionado;
    }
  
    
    public void resetearSeleccion(){
        l.iconoSeleccionado=-1;
    }
    
    public void setNombreIconos(String nombres){
        nombreIconos = nombres;
    }
    
    public String getNombreIconos(){      
        return nombreIconos;
    }
    
    public void cargarImagenes(){
        l.cargarImagenes();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(500, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
